### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Bhomitkapoor** [beingsaurabh/facial-recognition#1]
HI Saurabh, i am very excited to see the working of ur project?
Is it possible to contact you over skype or some other way?

Kind Regards,
Bhomit Kapoor

**Comment by Bhomitkapoor** [comment]
> HI Saurabh, i am very excited to see the working of ur project?
> Is it possible to contact you over skype or some other way?
> 
> Kind Regards,
> Bhomit Kapoor

waiting for ur reply
u can reply on my mail id - bk.bhomitkapoor@icloud.com

**Comment by beingsaurabh** [comment]
Hi 
I am glad that you liked my project . Are you a student as well ? What are your concerns regarding the project?
Thanks

**Comment by Bhomitkapoor** [comment]
Yes i am also a student
and want to ask you few questions over the quick call

**Comment by Bhomitkapoor** [comment]
can we connect over the skype today    
live:bk.bhomitkapoor_1
